spring:
  data:
    mongodb:
      uri: "mongodb+srv://rishitarana5:Rishita050@cluster0.w4atz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: collegeeasy5@gmail.com
    password: javamail
    # password: "xdnm bjcr bfxb uqyi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: 7502872ecb88bf5c333faf46b37f8ec1

# weather:
#   api:
#     key: ${WEATHER_API_KEY}



logging:
  level:
    org.springframework.mail: DEBUG





# # spring:
# #   profiles:
# #     active: dev

# spring:
#   data:
#     mongodb:
#       uri: "mongodb+srv://rishitarana5:Rishita050@cluster0.w4atz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
#       database: journaldb
#       auto-index-creation: true


# spring:
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: "collegeeasy5@gmail.com"
#     password: "xdnm bjcr bfxb uqyi"
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true

# server:
#   port: 8080
#   servlet:
#     context-path: /journal


# weather:
#   api:
#     key: 7502872ecb88bf5c333faf46b37f8ec1


